### ISSUE TITLE
Menu contains both English and Spanish links

### ISSUE THREAD

**Issue by jmilden-git** [Washington-County/COUNTY-DRUPAL#431]
Please make the menu so the user sees only the links for their current language choice.  Default is English. 
See: [https://dev.washingtoncountyor.gov/swr](https://dev.washingtoncountyor.gov/swr)

**Comment by jlwcor** [comment]
@jmilden-git @lgbridges 

I did a review and it's not combining Spanish and English translated pages.
It's all English items, but the menu link title set is in Spanish.

The menu settings is not a translatable item.
Please ensure that all Menu link titles are in the default English.

**Comment by jmilden-git** [comment]
The menu title was correct on each language version.  Something must have gone wrong to show a mix of English content with Sp menu title.

**Comment by jlwcor** [comment]
@jmilden-git it should only be in English. When you change it in Spanish, it gets applied to both English and Spanish. There is currently only one set.

**Comment by jmilden-git** [comment]
@jlwcor There are multiple problems with Spanish translated content and the menu.  None of these was a result of misconfiguration of content or a mix up by the Editor of the languages.  Something must have happened with the menu changes in a recent PR.  Please get @joshuami to help sort this out.
The Spanish links no longer display the corresponding content.

**Comment by jlwcor** [comment]
@jmilden-git that's because they are pointing to the English content that has a manually set Spanish title...
Custom menu translations isn't turned on...

So do the following:

- Replace the current menu link titles with English.
- I'll push out a PR that enables custom menu translations. 
- From there you will be able to add Spanish menu link titles while editing under /es

Does that make sense?

**Comment by jmilden-git** [comment]
@jlwcor No, sorry you're not making sense.  It's also the Legacy Path that got changed on the Eng versions.  That both didn't accidentally get placed there by the editor.  Why did it break, it was working when the content was first added.

**Comment by jlwcor** [comment]
@jmilden-git I'll fix the issue myself since you are having a difficult time understanding.

**Comment by joshuami** [comment]
@jlwcor , makes sense to me. On page, resource, and group, we should check the box for menu link at /admin/config/regional/content-language.

![image](https://user-images.githubusercontent.com/4097978/152261504-603b3749-7dfa-4847-9b96-9ec96f314dd8.png)

I wondered if just turning content translation on for menus would fix the issue, but it looks like there is a core issue suggesting that we might also need to turn on config translation to get menus to respond as they should: https://www.drupal.org/project/drupal/issues/3043226.

I remember the conversation about legacy paths not being language aware as well. That's really a separate issue... though I did just test adding a manual redirect at /admin/config/search/redirect/add and you can add redirects to an absolute path rather than a system path. So we might be able to refactor out custom legacy paths module a bit with a separate field that can add absolute redirects. It's not ideal if someone edits a short title and changes the alias, but it could be a start.
