### ISSUE TITLE
Moderation for image media types causing error.

### ISSUE THREAD

**Issue by gatoona** [Washington-County/COUNTY-DRUPAL#60]
PR #48 is causing issues when viewing the editing page for a media image content.

> Notice: Trying to get property 'value' of non-object in scheduler_content_moderation_integration_entity_access() (line 36 of modules/contrib/scheduler_content_moderation_integration/scheduler_content_moderation_integration.module).

You can replicate this issue by editing a media image entity. Error might not display on dev/stage/prod environments due to it being hidden, but it is entered in the Drupal log (/admin/reports/dblog).

This is because scheduler, integrated with workflow moderation is not applicable to media entities.

Solution is to remove media entities, images in this case, from workflow moderation.

**Comment by lgbridges** [comment]
Discussed with @gatoona and we have decided to remove the media workflow rather than engage an extended troubleshooting process regarding scheduler_content_moderation_integration module. We are unclear about the utility of being able to publish and unpublish images independently of the pages, news items, etc., that they appear in. We will advocate for deletion of media that authors would need to ensure are no longer available for public access.

Jung will remove the media workflow as part of his S3FS story.
